Integration specs
Ogaga01/Blog-App pull request #8
Opened 2023-05-15 12:03 UTC by Ogaga01

# Hello Reviewer 👋 

In this project milestone, I implemented the following requirements:
#### n+1
- Make sure that the N+1 problem is solved when fetching all posts and their comments for a user.
    - Do not use the bullet gem in this exercise - instead, analyze the logs as shown in this [article]
    - **In your PR description, include the screenshots of your app's logs before and after the fix**
    - This is the corresponding wireframe view:![blog all user posts](../images/blog_user_all_posts.png)

#### Integration specs
- Use Capybara to write integration tests for each view in your project.
- Think about the flow of things and group the tests of the page in a way that makes sense. For example, one test would check for the things on the page and another for clicking links
![Screenshot (7)](https://github.com/Ogaga01/Blog-App/assets/98261268/cc5bb102-ea00-4d96-8afc-815533c98d4c)
![Screenshot (8)](https://github.com/Ogaga01/Blog-App/assets/98261268/cfcbbab0-ae83-4153-bf18-c8eb3033a7e1)
![Screenshot (9)](https://github.com/Ogaga01/Blog-App/assets/98261268/5c523230-a6e1-4dd9-9e09-6058d5d5b2ab)
![Screenshot (10)](https://github.com/Ogaga01/Blog-App/assets/98261268/d2c388e9-986d-4df6-979b-7e28b7165f16)
.

- User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.

- user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.

- User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.

- Post-show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each comment.
  - I can see the comment each comment left.

**Include integration specs for any other features you may have implemented!**

2023-05-15 12:34 UTC, BregornOriginal reviewed
Hi @Ogaga01  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

***You have submitted a project, that doesn´t follow a `pair-programming` activity. You should ask your mate to help you with the test and do some commits to the project to be validated***

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-16 08:49 UTC, Davidosky007 requested changes
Hi @Ogaga01 @BregornOriginal 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* N+1 problems solved 👍 
* Well written PR 👍 
* No linter errors 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 08:49 UTC, Davidosky007 commented on spec/features/user_spec.rb
> +
* Kindly add a test to cover this `I can see the profile picture for each user.` as its missing

2023-05-16 08:49 UTC, Davidosky007 commented on spec/features/user_spec.rb
> +    end
* This test fails, Kindly fix it 
![image](https://github.com/Ogaga01/Blog-App/assets/52497246/af9e4d97-0fc4-4c12-81d6-17528d579759)
## Hints 💭 you can solve this test by targeting the actual 3posts you created for example 👇 
![image](https://github.com/Ogaga01/Blog-App/assets/52497246/4d215cb3-6b30-445e-af83-68c28af5f9cb)

2023-05-16 08:49 UTC, Davidosky007 commented on spec/features/user_spec.rb
> +    end
* Kindly write a test to cover this scenario `When I click a user's post, it redirects me to that post's show page` as its missing as its a [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md#:~:text=When%20I%20click%20a%20user%27s%20post%2C%20it%20redirects%20me%20to%20that%20post%27s%20show%20page)

2023-05-16 08:49 UTC, Davidosky007 commented on spec/features/post_spec.rb
> +      visit user_posts_path(@user_first.id)
* Kindly update your tests as some scenarios are missing below 👇 is a screenshot of the missing tests required 
![image](https://github.com/Ogaga01/Blog-App/assets/52497246/0c14f763-f77e-413d-91ef-0b13bc3191e4)

2023-05-16 08:49 UTC, Davidosky007 commented on spec/features/post_spec.rb
> +      expect(page).to have_content('This is my first post')
* These tests are failing , Kindly fix them 
![image](https://github.com/Ogaga01/Blog-App/assets/52497246/47934a0b-1f2c-4c86-ba3b-f1dca573a0cb)

2023-05-16 11:57 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @Ogaga01 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Solved n+1 problem 📌 
✔️ Good commit history
✔️ No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 11:57 UTC, codepantha commented on spec/features/user_spec.rb
> +    end
- [ ] This post is failing. Kindly fix it ✔️ 
![image](https://github.com/Ogaga01/Blog-App/assets/46839548/0c3d2f00-a7a0-4850-9a63-b82fb8d9ad46)

2023-05-16 11:57 UTC, codepantha commented on spec/features/post_spec.rb
> +    end
- [ ] This test is failing. Please try to make it pass ✔️ 
![image](https://github.com/Ogaga01/Blog-App/assets/46839548/7c1d96c6-4c3f-4edc-9293-6b0fba10c311)

2023-05-16 11:57 UTC, codepantha commented on spec/features/post_spec.rb
> +    end
- [ ] This test is not testing what it should be. Please write a test that actually asserts that a section for pagination is seen
![image](https://github.com/Ogaga01/Blog-App/assets/46839548/242ed860-1342-4280-95c2-07c749a60123)

2023-05-16 14:30 UTC, Gambit142 requested changes
Hi @Ogaga01 @jodavid444 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- Use of capybara gem to test for the project's features ✔️ 
- Wrote tests for _**Show**_ and _**Index**_ pages for `Post` and `User` controllers ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 14:30 UTC, Gambit142 commented on spec/features/post_spec.rb
> +    end
- [ ] The test for pagination is not correct as highlighted by the previous reviewer. On the `Post#Index` page, there ought to be a button to implement the _**Pagination feature**_. Even though it wasn't a hard requirement, the button ought to exist as a placeholder. It is the presence of the button on the `Post#Index` page that you ought to test for. Kindly implement this change. 👍 😎

2023-05-16 15:17 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 ✔️ 

## Hi @Ogaga01 👋, 

Great job implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 15:22 UTC, merged